RL.VGUI.RegisterFontAdv("DS-Digital", "Digi")
RL.VGUI.RegisterFontFixed("OPlusSans 3.0 Medium", "OPPOSans_F")
RL.VGUI.RegisterFontAdv("OPlusSans 3.0 Medium", "OPPOSans")
RL.VGUI.RegisterFontAdv("OPlusSans 3.0 Medium", "OPSans")
RL.VGUI.RegisterFontAdv("OPlusSans 3.0", "OPSans_L")
RL.VGUI.RegisterFontAdv("Source Han Sans SC", "SourceHan")
RL.VGUI.RegisterFontAdv("Smiley Sans Oblique", "SmileySans")