RL.VGUI.RegisterFont("DS-Digital", "Digi")
RL.VGUI.RegisterFontFixed("OPPOSans M", "OPPOSans_F")
RL.VGUI.RegisterFontAdv("OPPOSans M", "OPPOSans")
RL.VGUI.RegisterFontAdv("Source Han Sans SC", "SourceHan")
RL.VGUI.RegisterFontAdv("Smiley Sans Oblique", "SmileySans")